# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex_app', '0007_auto_20180420_1027'),
        ('login_registration', '0011_auto_20180420_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='used_in_teams', to='pokedex_app.Pokemon')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owns_teams', to='login_registration.User')),
            ],
        ),
    ]
