# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='used_in_teams', to='pokedex_app.Pokemon'),
        ),
    ]
