# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_ID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('pk_type', models.CharField(max_length=255)),
                ('pk_heigth', models.CharField(max_length=50)),
                ('pk_weigth', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
