# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_auto_20180419_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='PokeType',
        ),
    ]
