# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0003_auto_20180419_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='api_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pk_type',
            field=models.ManyToManyField(blank=True, related_name='pkmns', to='pokedex_app.PokeType'),
        ),
    ]
