# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0004_auto_20180419_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pk_ID',
            new_name='pk_id',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
