# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0005_auto_20180419_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pk_heigth',
            new_name='pk_height',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='pk_weigth',
            new_name='pk_weight',
        ),
    ]
