# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0006_auto_20180419_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pk_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pk_weight',
            field=models.FloatField(),
        ),
    ]
