# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='battles_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='battles_won',
            field=models.IntegerField(default=0),
        ),
    ]
