# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20180419_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
