# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0008_auto_20180420_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='static/img/user_pic/no-img.png', upload_to='static/img/user_pic/'),
        ),
    ]
