# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0009_auto_20180420_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
